### ISSUE TITLE
Example of transcoding video using VideoDecoder and VideoEncoder

### ISSUE THREAD

**Issue by kstreeter** [WICG/web-codecs#115] opened 2020-12-14 18:43 UTC
I have been experimenting with using WebCodecs to both decode and encoder H264 video, and I have been unable to encode frames (using VideoEncoder) that were original decoded using VideoDecoder.  It is possible I am doing something wrong, but I haven't been able to find a runnable example that shows this flow.

I am initializing the decoder like this:

``` typescript

        decoder.configure(
        { 
          codec : 'avc1.4d401e', 
          description : extra,
          codedWidth : 1280
          codedHeight : 720
          cropWidth : 1280,
          cropHeight : 720
      });

```

where `extra` contains the AVCC extra data.  I then send coded chunks to the decoder like this:

``` typescript

const isRAP = ...
const pts = ...

 let encodedChunk = new EncodedVideoChunk({
        type : isRAP ? "key" : "delta",
        timestamp: (pts / 30001) * 1000000,
        data: data
      });
      decoder.decode(encodedChunk);

```

where `isRAP` indicates whether this is a keyframe, the `pts` is the presentation timestamp in some timescale that gets converted to microseconds.  Both of these are provided by the container during demuxing.

This works, and I get decoded frames back.  I know it is decoding correctly, because I can call `createBitmapImage` on the frame and draw it to a canvas.

Next, it try to pass the frame to the encoder.  The encoder is configured like this:

``` typescript

encoder.configure({
      codec : 'avc1.4d401e',
      width : 1280,
      height : 720,
      bitrate : 1000000,
      framerate : 30
      });

```

I attempt to encode each frame coming from the decoder, like this:

``` typescript

function onDecodeWCFrame(frame : any){

    encoder.add(frame); // also tried frame.clone() here, same result

}

```

This results in an error callback from the encoder, which states `OperationError: Encoding error.`

I had expected passing the same frame I got from the decoder to work, but that might be a bad assumption.  I considered creating a new VideoFrame from the decoded frame, but decoded frame returns `null` for properties such as format and planes (which appears to be a known issue), so there is no way to configure a new frame (without doing something wasteful like converting it to a bitmap and then converting it back to YUV).

Are there any working examples of doing this kind of transcoding I could use to check my implementation?

**Comment by chcunningham** [comment] 2020-12-14 20:53
> I had expected passing the same frame I got from the decoder to work, but that might be a bad assumption
This is a great assumption! We consider any point where that fails to be a bug. 

Unfortunately you're bumping into an area of the impl that is not yet documented. 

The encoder currently defaults to produce a format of AVC that is typical of mp4 files, where you need the info from the avcC atom to completely describe the stream. That info will be provided to you via the VideoDecoderConfig that we emit as the second (undocumented) argument in the encoder output callback. In particular, the VideoDecoderConfig description field will have the avcC info. 

I'm actively [updating the spec to reflect this](https://github.com/WICG/web-codecs/pull/113). Note that the spec update will only emit a decoder config when things change, and give a null config otherwise. Chromium's current impl will actually emit the config on every frame (we'll fix that). 

I don't have a good demo for transcoding AVC, but if you take [this demo](https://webcodecs-blogpost-demo.glitch.me/) and change the codec to avc, and take care to grab the VideoDecoderConfig from the encoder output callback as described above, it should work. Please let us know!

**Comment by kstreeter** [comment] 2020-12-14 21:55
Thanks for the response @chcunningham.  

To clarify, I am actually not trying to pass data from the encoder to the decoder, I wish to go the other way around, taking a decoded frame output from VideoDecoder and passing it into a VideoEncoder.  The demo app you referred doesn't really do that, as it gets frames out of a VideoTrackReader versus from a VideoDecoder instance.

It is definitely good to know that the avcC info is being emitted from the encoder though...I had been afraid I was going to have to parse that out of AnnexB output or just manufacture it manually, so thank you for the pointer!

**Comment by chcunningham** [comment] 2020-12-14 22:29
Apologies, read way too fast! I follow you now and I'm not immediately sure whats causing your error. I will make a demo to do what you described and see if I can reproduce. Meanwhile, if its easy for you to upload your script I'd be happy to take a closer look.

**Comment by kstreeter** [comment] 2020-12-14 23:08
Yes I spent a little time making a shareable repro case.  I hacked up @tguilbert-google 's demux demo and added the encoding step: https://kstreeter.github.io/wctranscode/.

Run this on Chrome Version 89.0.4350.0 (Official Build) canary (x86_64) and you should see "Encoding error: OperationError: Encoding error." logged to the console.

**Comment by chcunningham** [comment] 2020-12-15 04:01
You found a bug! We appear to have some issue encoding VideoFrames that originate from our hardware accelerated video decoders. Your demo works for me if I go to chrome://flags/#disable-accelerated-video-decode and "Disable" accelerated video decoding. LMK if you see the same. 

Filed a bug to fix Chrome here
https://bugs.chromium.org/p/chromium/issues/detail?id=1158665

**Comment by kstreeter** [comment] 2020-12-15 17:34
Yes confirmed turning off hardware video decode resolves the issue.  Thank you for filing the bug report!

**Comment by chcunningham** [comment] 2020-12-15 17:52
Awesome. I'll leave this open for a bit just to give this issue visibility. Thanks a ton for the demo.

**Comment by chcunningham** [comment] 2021-02-19 19:44
Closing now that its been a while. Fix in chrome goes out with v 89. Thanks again for filing!

**Closed by chcunningham** 2021-02-19 19:44 UTC
