### ISSUE TITLE
Add support for layer taget bitrate for SVC RTC

### ISSUE THREAD

**Issue by marco99zz** [WICG/web-codecs#84] opened 2020-10-05 18:00 UTC
For SVC in RTC, each spatial-temporal layer must have be given its own target bitrate. Encoders like libvpx-VP9 use this for layered CBR rate control, to ensure each layer hits the specified target bitrate. 

Is this already supported or is there a plan to add this?

**Comment by sandersdan** [comment] 2020-10-05 18:41
Duplicate of #40

**Closed by sandersdan** 2020-10-05 18:41 UTC
